# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: love.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlove.proto\x12\x04love\"\x19\n\x05Input\x12\x10\n\x08\x61pproach\x18\x01 \x01(\x0c\"\x1c\n\x06Output\x12\x12\n\nacceptance\x18\x01 \x01(\x0c\x32-\n\x08LoveGrpc\x12!\n\x04Love\x12\x0b.love.Input\x1a\x0c.love.Outputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'love_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=20
  _globals['_INPUT']._serialized_end=45
  _globals['_OUTPUT']._serialized_start=47
  _globals['_OUTPUT']._serialized_end=75
  _globals['_LOVEGRPC']._serialized_start=77
  _globals['_LOVEGRPC']._serialized_end=122
# @@protoc_insertion_point(module_scope)
