version: '3.7'
services:
  grpc_server:
    build:
      context: ./image_grpc_server
      dockerfile: Dockerfile
    container_name: grpc_server
    command: python server.py
    volumes:
      - .:/server
    ports:
      - 6000:6000
    restart: always
  grpc_client:
    build:
      context: ./image_grpc_client
      dockerfile: Dockerfile
    container_name: grpc_client
    command: uvicorn main:app --reload
    volumes:
      - .:/client
    ports:
      - 8010:8010
    restart: always